apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: Bui-Tien-Dat-2808/api-gateway:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "-m", "uvicorn", "api_gateway:app", "--host", "0.0.0.0", "--port", "9000"]
          ports:
            - containerPort: 9000
          env:
            - name: CONSUL_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-configmap
                  key: CONSUL_URL
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30000  # Cổng tĩnh để test từ ngoài cluster
  selector:
    app: api-gateway
