apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: Bui-Tien-Dat-2808/order-service:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "-m", "uvicorn", "services.order_service.app.main:app", "--host", "0.0.0.0", "--port", "8003"]
          ports:
            - containerPort: 8003
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/orders_db"
            - name: CONSUL_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-configmap
                  key: CONSUL_URL
            - name: SERVICE_NAME
              value: "order-service"
            - name: SERVICE_PORT
              value: "8003"
            - name: SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  ports:
    - port: 8003
      targetPort: 8003
  selector:
    app: order-service
