apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: dat2808/payment-service:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "-m", "uvicorn", "services.payment_service.app.main:app", "--host", "0.0.0.0", "--port", "8004"]
          ports:
            - containerPort: 8004
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/payments_db"
            - name: CONSUL_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-configmap
                  key: CONSUL_URL
            - name: SERVICE_NAME
              value: "payment-service"
            - name: SERVICE_PORT
              value: "8004"
            - name: SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  ports:
    - port: 8004
      targetPort: 8004
  selector:
    app: payment-service