apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres-service -p 5432 -U postgres; do
                echo "Waiting for postgres..."
                sleep 2
              done
      containers:
        - name: user-service
          image: dat2808/user-service:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "-m", "uvicorn", "services.user_service.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/users_db"
            - name: CONSUL_URL
              valueFrom:
                configMapKeyRef:
                  name: ecom-configmap
                  key: CONSUL_URL
            - name: SERVICE_NAME
              value: "user-service"
            - name: SERVICE_PORT
              value: "8000"
            - name: SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: user-service